FROM python:3.9.1-buster

LABEL Joshua S. Eagle

WORKDIR /root/

COPY ./python-service/ /root/python-service/

WORKDIR /root/python-service/

RUN pip install flask gpio pyyaml

CMD ["python", "app.py"]
