FROM node:14.20.1-slim

LABEL Joshua S. Eagle

WORKDIR /root/

COPY ./node-service /root/node-service/

WORKDIR /root/node-service/

RUN apt-get update && apt-get install -y build-essential python

RUN \
npm i -g nodemon && \
npm i

CMD ["npm", "run", "start"]
