FROM node:14.20.1-slim

LABEL Joshua S. Eagle

WORKDIR /root/

COPY ./ng-app /root/ng-app

WORKDIR /root/ng-app

RUN \
npm i -g @angular/cli && \
npm i && \
npm run build

CMD ["npm", "run", "docker-start"]
